---
- hosts: dev
  become: True
  tasks:
   - name: Install docker
     apt: 
       name: docker.io
       state: present
   - name: Install python3 
     apt:
       name: python3
       state: present
   - name: Start docker
     service:
       name: docker
       state: started
       enabled: yes
   - name: Install python3-docker module
     apt: 
       name: python3-docker
       state: present
   - name: Kill old container
     command: "docker stop $(docker ps -a -q)"
     command: "docker image prune -a -f"
   - name: Get a list of all running containers
     docker_host_info:
       containers: True
     register: docker_info
   - name: Stop all running containers
     docker_container:
       name: '{{ item.Names[0] | regex_replace("^/", "") }}'
       state: stopped
     loop: '{{ docker_info.containers }}'
   - name: Remove images
     command: docker image rm -f nkasperskyi/webapp:v1.0
   #- name: stop container 
   #  shell: docker stop webapp
   #- name: remove container remove image
   #  shell: docker rm -f webapp
   #- name: remove image
   #  shell: docker image rm -f nkasperskyi/webapp   
   - name: Start container nkasperskyi/webapp
     shell: docker run -d --rm -p 8090:8080 nkasperskyi/webapp:v1.0
       #name: webapp
       #image: "nkasperskyi/webapp:v1.0"
       #state: started
       #published_ports:
       #  - 0.0.0.0:8090:8080